### ISSUE TITLE
java.lang.NullPointerException: Cannot invoke "rotp.model.colony.Colony.governIfNeeded()" because ....

### ISSUE THREAD

**Issue by frank-zago** [BrokenRegistry/Rotp-Fusion#117]
To reproduce the following:
- abandon a planet, wait a turn. The planet will be marked as "abandonned"
- send new troups to that planet. Immediate crash.

(I'm also unconvinced new colons can be sent to an abandoned planet as-is, but that might be a feature.)

Error Cannot invoke "rotp.model.colony.Colony.governIfNeeded()" because the return value of "rotp.model.galaxy.StarSystem.colony()" is null in thread AWT-EventQueue-0
java.lang.NullPointerException: Cannot invoke "rotp.model.colony.Colony.governIfNeeded()" because the return value of "rotp.model.galaxy.StarSystem.colony()" is null
	at rotp.model.colony.Colony.scheduleTransportsToSystem(Colony.java:1398)
	at rotp.ui.sprites.SystemTransportSprite.accept(SystemTransportSprite.java:72)
	at rotp.model.empires.Empire.deployTransport(Empire.java:963)
	at rotp.ui.main.TransportDeploymentPanel.acceptTransport(TransportDeploymentPanel.java:228)
	at rotp.ui.main.TransportDeploymentPanel$TransportButtonPane.mouseReleased(TransportDeploymentPanel.java:990)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6621)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3398)
	at java.desktop/java.awt.Component.processEvent(Component.java:6386)
	at java.desktop/java.awt.Container.processEvent(Container.java:2266)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:4996)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4828)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4948)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4575)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4516)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2310)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2780)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4828)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:775)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:720)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:714)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:98)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:747)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:744)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

**Comment by BrokenRegistry** [comment]
I've never used this feature, and it seems it's not used very much, since the bug has existed since the governor was added!
Fixed.
