### ISSUE TITLE
ava.lang.NullPointerException: Cannot invoke "rotp.model.empires.Empire.minActiveDesignSpeed()" because "player" is null

### ISSUE THREAD

**Issue by frank-zago** [BrokenRegistry/Rotp-Fusion#122]
No idea how to reproduce.

Error Cannot invoke "rotp.model.empires.Empire.minActiveDesignSpeed()" because "player" is null in thread AWT-EventQueue-0
java.lang.NullPointerException: Cannot invoke "rotp.model.empires.Empire.minActiveDesignSpeed()" because "player" is null
	at rotp.model.game.IInGameOptions.chainRallySpeed(IInGameOptions.java:240)
	at rotp.model.empires.SystemView.rallyNearestSystem(SystemView.java:224)
	at rotp.model.empires.SystemInfo.rallyNearestSystem(SystemInfo.java:132)
	at rotp.ui.fleets.SystemMassRallyPanel.startRallyToGates(SystemMassRallyPanel.java:103)
	at rotp.ui.fleets.SystemMassRallyPanel$SystemRallyFooterPane.paintComponent(SystemMassRallyPanel.java:230)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1128)
	at rotp.ui.BasePanel.paint(BasePanel.java:146)
	at java.desktop/javax.swing.JComponent.paintToOffscreen(JComponent.java:5318)
	at java.desktop/javax.swing.RepaintManager$PaintManager.paintDoubleBufferedImpl(RepaintManager.java:1656)
	at java.desktop/javax.swing.RepaintManager$PaintManager.paintDoubleBuffered(RepaintManager.java:1631)
	at java.desktop/javax.swing.RepaintManager$PaintManager.paint(RepaintManager.java:1569)
	at java.desktop/javax.swing.BufferStrategyPaintManager.paint(BufferStrategyPaintManager.java:271)
	at java.desktop/javax.swing.RepaintManager.paint(RepaintManager.java:1336)
	at java.desktop/javax.swing.JComponent._paintImmediately(JComponent.java:5266)
	at java.desktop/javax.swing.JComponent.paintImmediately(JComponent.java:5076)
	at java.desktop/javax.swing.RepaintManager$4.run(RepaintManager.java:878)
	at java.desktop/javax.swing.RepaintManager$4.run(RepaintManager.java:861)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
	at java.desktop/javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:861)
	at java.desktop/javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:834)
	at java.desktop/javax.swing.RepaintManager.prePaintDirtyRegions(RepaintManager.java:784)
	at java.desktop/javax.swing.RepaintManager$ProcessingRunnable.run(RepaintManager.java:1897)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:720)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:714)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

**Comment by BrokenRegistry** [comment]
Thanks for the report, it was sufficient to pinpoint the bug.
Fixed.
