### ISSUE TITLE
java.lang.NullPointerException: Cannot read field "empId" because "fl" is null

### ISSUE THREAD

**Issue by frank-zago** [BrokenRegistry/Rotp-Fusion#58]
I got several of these when running in debug mode:

Error Cannot read field "empId" because "fl" is null in thread AWT-EventQueue-0
java.lang.NullPointerException: Cannot read field "empId" because "fl" is null
	at rotp.model.galaxy.Ships.allFleets(Ships.java:697)
	at rotp.model.empires.Empire.inVisibleRange(Empire.java:2530)
	at rotp.model.empires.Empire.hiddenSystem(Empire.java:2517)
	at rotp.model.galaxy.StarSystem.draw(StarSystem.java:634)
	at rotp.ui.main.GalaxyMapPanel.drawStarSystems(GalaxyMapPanel.java:876)
	at rotp.ui.main.GalaxyMapPanel.paintToImage(GalaxyMapPanel.java:380)
	at rotp.ui.main.GalaxyMapPanel.paintComponent(GalaxyMapPanel.java:315)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1128)
	at rotp.ui.BasePanel.paint(BasePanel.java:152)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:961)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1137)
	at java.desktop/javax.swing.JLayeredPane.paint(JLayeredPane.java:586)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:961)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1137)
	at rotp.ui.BasePanel.paint(BasePanel.java:152)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:961)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1137)
	at rotp.ui.BasePanel.paint(BasePanel.java:152)
	at rotp.ui.RotPUI.paint(RotPUI.java:385)
	at java.desktop/javax.swing.JComponent.paintToOffscreen(JComponent.java:5318)
	at java.desktop/javax.swing.RepaintManager$PaintManager.paintDoubleBufferedImpl(RepaintManager.java:1656)
	at java.desktop/javax.swing.RepaintManager$PaintManager.paintDoubleBuffered(RepaintManager.java:1631)
	at java.desktop/javax.swing.RepaintManager$PaintManager.paint(RepaintManager.java:1569)
	at java.desktop/javax.swing.BufferStrategyPaintManager.paint(BufferStrategyPaintManager.java:271)
	at java.desktop/javax.swing.RepaintManager.paint(RepaintManager.java:1336)
	at java.desktop/javax.swing.JComponent._paintImmediately(JComponent.java:5266)
	at java.desktop/javax.swing.JComponent.paintImmediately(JComponent.java:5076)
	at java.desktop/javax.swing.RepaintManager$4.run(RepaintManager.java:878)
	at java.desktop/javax.swing.RepaintManager$4.run(RepaintManager.java:861)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
	at java.desktop/javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:861)
	at java.desktop/javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:834)
	at java.desktop/javax.swing.RepaintManager.prePaintDirtyRegions(RepaintManager.java:784)
	at java.desktop/javax.swing.RepaintManager$ProcessingRunnable.run(RepaintManager.java:1897)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:720)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:714)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

**Comment by BrokenRegistry** [comment]
Yes, as implied by the name, "Debug options" are not secure and validated" as safe, secure and validated as the the other options. This because they allow some forbiden actions that may corrupt the memory. (Still some mystery there)
I added a security test for this one, and some other alike... Some time it will be enough, some time not.
