### ISSUE TITLE
Error Index 0 out of bounds for length 0 in thread AWT-EventQueue-0

### ISSUE THREAD

**Issue by frank-zago** [BrokenRegistry/Rotp-Fusion#62]
Zooming out on the galaxy after exiting autorun mode.

Error Index 0 out of bounds for length 0 in thread AWT-EventQueue-0
java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:100)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:106)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:302)
	at java.base/java.util.Objects.checkIndex(Objects.java:385)
	at java.base/java.util.ArrayList.get(ArrayList.java:427)
	at rotp.model.empires.Empire.defaultSystem(Empire.java:1238)
	at rotp.ui.planets.PlanetsUI.lastSelectedSystem(PlanetsUI.java:989)
	at rotp.ui.planets.PlanetsUI.allSystems(PlanetsUI.java:829)
	at rotp.ui.planets.PlanetsUI.access$1700(PlanetsUI.java:82)
	at rotp.ui.planets.PlanetsUI$PlanetDataListingUI.systems(PlanetsUI.java:2068)
	at rotp.ui.fleets.SystemListingUI.open(SystemListingUI.java:126)
	at rotp.ui.planets.PlanetsUI.init(PlanetsUI.java:148)
	at rotp.ui.RotPUI.selectPlanetsPanel(RotPUI.java:497)
	at rotp.ui.main.MainButtonPanel.clickButton(MainButtonPanel.java:214)
	at rotp.ui.main.MainButtonPanel.mouseReleased(MainButtonPanel.java:274)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6621)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3398)
	at java.desktop/java.awt.Component.processEvent(Component.java:6386)
	at java.desktop/java.awt.Container.processEvent(Container.java:2266)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:4996)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4828)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4948)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4575)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4516)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2310)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2780)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4828)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:775)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:720)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:714)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:98)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:747)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:744)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

**Comment by frank-zago** [comment]
The simulated player had lost, but the game kept going on.

**Comment by BrokenRegistry** [comment]
Yes, the game keep going when the debug option "Continue on Defeat" is set to "Always".

This time the thread tha remove the player was quicker than the one displaying the map... (Never happen on my computer)
This condition is now tested, and the map has now a valid system to center on.

**Comment by BrokenRegistry** [comment]
Fixed
