### ISSUE TITLE
Error Index 2 out of bounds for length 1 in thread AWT-EventQueue-0

### ISSUE THREAD

**Issue by frank-zago** [BrokenRegistry/Rotp-Fusion#64]
That one happened immediatelly when I clicked on "Continue" on the main screen. That's new. Never seen it before.

Error Index 2 out of bounds for length 1 in thread AWT-EventQueue-0
java.lang.IndexOutOfBoundsException: Index 2 out of bounds for length 1
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:100)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:106)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:302)
	at java.base/java.util.Objects.checkIndex(Objects.java:385)
	at java.base/java.util.ArrayList.get(ArrayList.java:427)
	at rotp.model.empires.Race.nameVariant(Race.java:340)
	at rotp.model.empires.Empire.unparsedRaceName(Empire.java:263)
	at rotp.model.empires.Empire.raceName(Empire.java:274)
	at rotp.model.empires.Empire.raceName(Empire.java:270)
	at rotp.model.empires.Empire.draw(Empire.java:4898)
	at rotp.model.empires.Empire.draw(Empire.java:4880)
	at rotp.ui.map.IMapHandler.drawEmpireName(IMapHandler.java:114)
	at rotp.ui.main.GalaxyMapPanel.drawEmpireNames(GalaxyMapPanel.java:860)
	at rotp.ui.main.GalaxyMapPanel.paintToImage(GalaxyMapPanel.java:385)
	at rotp.ui.main.GalaxyMapPanel.paintComponent(GalaxyMapPanel.java:315)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1128)
	at rotp.ui.BasePanel.paint(BasePanel.java:152)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:961)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1137)
	at java.desktop/javax.swing.JLayeredPane.paint(JLayeredPane.java:586)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:961)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1137)
	at rotp.ui.BasePanel.paint(BasePanel.java:152)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:961)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1137)
	at rotp.ui.BasePanel.paint(BasePanel.java:152)
	at rotp.ui.RotPUI.paint(RotPUI.java:385)
	at java.desktop/javax.swing.JComponent.paintToOffscreen(JComponent.java:5318)
	at java.desktop/javax.swing.RepaintManager$PaintManager.paintDoubleBufferedImpl(RepaintManager.java:1656)
	at java.desktop/javax.swing.RepaintManager$PaintManager.paintDoubleBuffered(RepaintManager.java:1631)
	at java.desktop/javax.swing.RepaintManager$PaintManager.paint(RepaintManager.java:1569)
	at java.desktop/javax.swing.BufferStrategyPaintManager.paint(BufferStrategyPaintManager.java:271)
	at java.desktop/javax.swing.RepaintManager.paint(RepaintManager.java:1336)
	at java.desktop/javax.swing.JComponent._paintImmediately(JComponent.java:5266)
	at java.desktop/javax.swing.JComponent.paintImmediately(JComponent.java:5076)
	at java.desktop/javax.swing.RepaintManager$4.run(RepaintManager.java:878)
	at java.desktop/javax.swing.RepaintManager$4.run(RepaintManager.java:861)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
	at java.desktop/javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:861)
	at java.desktop/javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:834)
	at java.desktop/javax.swing.RepaintManager.prePaintDirtyRegions(RepaintManager.java:784)
	at java.desktop/javax.swing.RepaintManager$ProcessingRunnable.run(RepaintManager.java:1897)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:720)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:714)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

**Comment by frank-zago** [comment]
It might have happened because I loaded a previous debug game where the race was extinct.
After starting a new game, I couldn't reproduce.

**Comment by BrokenRegistry** [comment]
Not a perfect fix, but preventing all the "Debug" crash is far to complex, and may block some debug testing...

Added Warning for the option "Continue on defeat": Reloading a game with a dead player will crash the game.
